site_name: AutoDev Vault
theme:
  name: material
  palette:
    scheme: slate  # dark theme by default
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    logo: material/car  # or change to any Material Icon
extra_css:
  - styles/override.css
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap

nav:
  - Home: index.md
  - Model-Based Development (MBD): mbd.md
  - Code-Based Development (CBD): cbd.md
  - Simulink: simulink.md
  - Stateflow: stateflow.md
  - AUTOSAR & RTE: autsar.md
  - PolySpace & SonarQube: polyspace.md
  - Tools & Scripting: tools.md
  - Testing & Safety: testing.md
  - System Design & Integration: system.md
