site_name: AutoDev Vault

nav:
  - Home: index.md
  - Model-Based Development (MBD): MBD.md
  - Code-Based Development (CBD): CBD.md
  - Simulink: Simulink.md
  - Stateflow: Stateflow.md
  - AUTOSAR & RTE: autsar.md
  - PolySpace & SonarQube: polyspace.md
  - Tools & Scripting: tools.md
  - Testing & Safety: testing.md
  - System Design & Integration: system.md
