site_name: "🚗 AutoDev Vault by Mahija"
theme:
  name: material
  features:
    - navigation.tabs  # helps organize topbar
    - navigation.top
  

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs   # REMOVE this line if present
  palette:
    scheme: slate
    primary: pink
    accent: yellow

nav:
  - Home: index.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
